### PR TITLE
Add osx support

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Comment by jakirkham** [comment]
Hmm...

@conda-forge-admin, please rerender. :)

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Comment by marcelotrevisani** [comment]
I will merge that, if you have any suggestion please let me know  :)

**Comment by jakirkham** [comment]
Thanks @marcelotrevisani.

Sorry I've been slow. Am at a sprint this week.

No real suggestions from me. Generally this looks good. Thanks for getting working macOS builds for these. 😄

**Comment by marcelotrevisani** [comment]
Hi @jakirkham , no problem at all! I know that you are very busy! 

It was just to be sure that everything was ok. Thanks! :)

**Pull request merged**
